# Simplified GitLab CE Configuration
global:
  # Domain configuration
  hosts:
    domain: awsraja.win
    gitlab:
      name: git.awsraja.win
  
  # Edition
  edition: ce
  
  # Ingress configuration for ALB
  ingress:
    enabled: true
    class: alb
    annotations:
      alb.ingress.kubernetes.io/scheme: internet-facing
      alb.ingress.kubernetes.io/target-type: ip
      alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
      alb.ingress.kubernetes.io/ssl-redirect: '443'
      # Add your certificate ARN here after creating it
      # alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-west-2:221734559126:certificate/YOUR-CERT-ID
    tls:
      enabled: false  # Disable for now, enable after cert setup
  
  # Time zone
  time_zone: UTC

# Disable components not needed for simple setup
prometheus:
  install: false

grafana:
  enabled: false

gitlab-runner:
  install: false

certmanager:
  install: false

certmanager-issuer:
  email: your-email@example.com  # Replace with your actual email

# Simplified PostgreSQL configuration
postgresql:
  install: true
  auth:
    username: gitlab
    database: gitlab
    password: "gitlabpassword123"  # Simple password
  primary:
    persistence:
      enabled: true
      size: 20Gi
    resources:
      requests:
        memory: 512Mi
        cpu: 250m
      limits:
        memory: 1Gi
        cpu: 500m

# Simplified Redis configuration
redis:
  install: true
  auth:
    enabled: true
    password: "redispassword123"  # Simple password
  master:
    persistence:
      enabled: true
      size: 8Gi
    resources:
      requests:
        memory: 256Mi
        cpu: 100m
      limits:
        memory: 512Mi
        cpu: 200m

# Simplified GitLab configuration
gitlab:
  webservice:
    replicaCount: 1  # Single replica for simplicity
    resources:
      requests:
        memory: 1.5Gi
        cpu: 500m
      limits:
        memory: 3Gi
        cpu: 1000m
  
  sidekiq:
    replicaCount: 1
    resources:
      requests:
        memory: 512Mi
        cpu: 250m
      limits:
        memory: 1Gi
        cpu: 500m
  
  gitaly:
    persistence:
      enabled: true
      size: 50Gi
    resources:
      requests:
        memory: 512Mi
        cpu: 250m
      limits:
        memory: 1Gi
        cpu: 500m

# Simplified Registry configuration
registry:
  enabled: true
  storage:
    size: 20Gi

# Simplified MinIO configuration
minio:
  persistence:
    enabled: true
    size: 20Gi

# Nginx configuration - disabled since using ALB
nginx-ingress:
  enabled: false
