# GitLab CE with Cloudflare SSL
global:
  hosts:
    domain: awsraja.win
    gitlab:
      name: git.awsraja.win
  
  edition: ce
  
  # Disable ingress - use LoadBalancer instead
  ingress:
    enabled: false
  
  # Time zone
  time_zone: UTC

# Use LoadBalancer (works with Cloudflare)
nginx-ingress:
  enabled: true
  controller:
    service:
      type: LoadBalancer
      annotations:
        service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
        service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
      ports:
        http: 80
        https: 443
    config:
      use-forwarded-headers: "true"
      compute-full-forwarded-for: "true"
      use-proxy-protocol: "false"

# DISABLE cert-manager completely
certmanager:
  install: false

# Fix for the cert-manager-issuer email error
certmanager-issuer:
  email: your-email@example.com  # Required even when disabled

# Disable other complex components
prometheus:
  install: false

grafana:
  enabled: false

gitlab-runner:
  install: false

# Simplified PostgreSQL
postgresql:
  install: true
  auth:
    username: gitlab
    database: gitlab
    password: "gitlabpass123"
  primary:
    persistence:
      enabled: true
      size: 20Gi
    resources:
      requests:
        memory: 512Mi
        cpu: 250m
      limits:
        memory: 1Gi
        cpu: 500m

# Simplified Redis
redis:
  install: true
  auth:
    enabled: true
    password: "redispass123"
  master:
    persistence:
      enabled: true
      size: 8Gi
    resources:
      requests:
        memory: 256Mi
        cpu: 100m
      limits:
        memory: 512Mi
        cpu: 200m

# GitLab components
gitlab:
  webservice:
    replicaCount: 1
    resources:
      requests:
        memory: 1.5Gi
        cpu: 500m
      limits:
        memory: 3Gi
        cpu: 1000m
  
  sidekiq:
    replicaCount: 1
    resources:
      requests:
        memory: 512Mi
        cpu: 250m
      limits:
        memory: 1Gi
        cpu: 500m
  
  gitaly:
    persistence:
      enabled: true
      size: 50Gi
    resources:
      requests:
        memory: 512Mi
        cpu: 250m
      limits:
        memory: 1Gi
        cpu: 500m

  toolbox:
    replicas: 1

# Simplified registry
registry:
  enabled: true
  storage:
    size: 20Gi

# Simplified MinIO
minio:
  persistence:
    enabled: true
    size: 20Gi
