# gitlab-values.yaml
global:
  # Domain configuration
  hosts:
    domain: awsraja.win
    hostSuffix: 
    gitlab:
      name: git.awsraja.win
    registry:
      name: registry.git.awsraja.win
    minio:
      name: minio.git.awsraja.win
  
  # Ingress configuration for ALB
  ingress:
    enabled: true
    class: alb
    annotations:
      alb.ingress.kubernetes.io/scheme: internet-facing
      alb.ingress.kubernetes.io/target-type: ip
      alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
      alb.ingress.kubernetes.io/ssl-redirect: '443'
      alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:REGION:ACCOUNT:certificate/CERTIFICATE-ID
      alb.ingress.kubernetes.io/load-balancer-name: gitlab-alb
    tls:
      enabled: true
      secretName: gitlab-tls
  
  # Edition
  edition: ce
  
  # Time zone
  time_zone: UTC
  
  # External URLs
  external_url: https://git.awsraja.win
  
  # Storage configuration
  psql:
    connectTimeout: 
    password: {}
    host: 
    port: 
    username: 
    database: 
  
  redis:
    password: {}
    host: 
    port: 
  
  # Resource configurations
  common:
    labels: {}
  
  # Security context
  securityContext:
    runAsUser: 1000
    fsGroup: 1000

# Disable components not needed for basic setup
prometheus:
  install: false

grafana:
  enabled: false

gitlab-runner:
  install: false

# PostgreSQL configuration
postgresql:
  install: true
  auth:
    username: gitlab
    database: gitlab
    existingSecret: gitlab-postgresql-password
  primary:
    persistence:
      enabled: true
      storageClass: gitlab-storage
      size: 50Gi
    resources:
      requests:
        memory: 1Gi
        cpu: 500m
      limits:
        memory: 2Gi
        cpu: 1000m

# Redis configuration
redis:
  install: true
  auth:
    enabled: true
    existingSecret: gitlab-redis-secret
    existingSecretPasswordKey: password
  master:
    persistence:
      enabled: true
      storageClass: gitlab-storage
      size: 8Gi
    resources:
      requests:
        memory: 512Mi
        cpu: 250m
      limits:
        memory: 1Gi
        cpu: 500m

# GitLab configuration
gitlab:
  # Webservice configuration
  webservice:
    replicaCount: 2
    resources:
      requests:
        memory: 2Gi
        cpu: 1000m
      limits:
        memory: 4Gi
        cpu: 2000m
    
  # Sidekiq configuration
  sidekiq:
    replicaCount: 1
    resources:
      requests:
        memory: 1Gi
        cpu: 500m
      limits:
        memory: 2Gi
        cpu: 1000m
  
  # Gitaly configuration
  gitaly:
    persistence:
      enabled: true
      storageClass: gitlab-storage
      size: 100Gi
    resources:
      requests:
        memory: 1Gi
        cpu: 500m
      limits:
        memory: 2Gi
        cpu: 1000m

# Registry configuration
registry:
  enabled: true
  storage:
    storageClass: gitlab-storage
    size: 30Gi

# MinIO configuration
minio:
  persistence:
    enabled: true
    storageClass: gitlab-storage
    size: 50Gi

# Nginx configuration
nginx-ingress:
  enabled: false  # We're using ALB

# Certmanager (disabled as we're using ACM)
certmanager:
  install: false

# Issuer for Let's Encrypt (if not using ACM)
certmanager-issuer:
  email: your-email@example.com  # Replace with your email
